### ISSUE TITLE
Edit historic maps of Europe that show border changes between 1750-1930

### ISSUE THREAD

**Issue by markdturner** [ATNU/translations#1]

**Comment by markdturner** [comment]
Some maps are available at http://www.ieg-maps.de/map2.htm

**Comment by fiona-galston** [comment]
Changed to edit the maps
- white space removal
- some need re-georeferencing e.g. 1874 as they're more off than the others

**Comment by fiona-galston** [comment]
done, white space removed and all geo-referenced
