### ISSUE TITLE
Add timeline slider

### ISSUE THREAD

**Issue by markdturner** [ATNU/translations#2]
Use timeline as the primary way of navigating through the data

**Comment by markdturner** [comment]
The best way forward is to use the Material slider as the means on input, using the API to programmatically move the slider if the user presses the play button. Documentation for the slider can be found [here](https://material.angular.io/components/slider/overview)

**Comment by markdturner** [comment]
The timeline needs the following features
- [x] Positioned with a scale to show both the start and end dates, as well as intermediate dates
- [x] User can drag the slider to modify the selected map
- [x] User can press a play/pause button to move through the sequence on maps in order

**Comment by fiona-galston** [comment]
play works
pause and refresh needed 
intermediate dates should be changed - ask Thiago/Laura/James about preference

**Comment by fiona-galston** [comment]
Play and Pause working

**Comment by fiona-galston** [comment]
refresh working

**Comment by fiona-galston** [comment]
Play, pause, refresh work
TImeline is clickable which changes the date, if timeline is clicked during play, this pauses and sets to selected date
Markers on timeline have been changed to reflect intermediate dates and ticks reflect a selection of years with a large amount of data
